version: '3.9'
services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "3001:16686"

  postgres-tenant:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  echo-server:
      build:
        context: https://github.com/WalletConnect/echo-server.git
      depends_on:
        - jaeger
        - postgres
      ports:
        - "3000:3000"
        - "3002:3002"
      environment:
        - PORT=3000
        - LOG_LEVEL=info,echo-server=info
        - LOG_LEVEL_OTEL=info,echo-server=trace
        - DATABASE_URL=postgres://postgres:root@postgres:5432/postgres
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
        - TELEMETRY_PROMETHEUS_PORT=3002
        - OTEL_SERVICE_NAME=echo-server
        - OTEL_RESOURCE_ATTRIBUTES=environment=dev,region=local,version=0.11.5
        - OTEL_TRACES_SAMPLER=always_on

        - PUBLIC_URL=https://echo.walletconnect.com
        - DISABLE_HEADER=false
        - RELAY_PUBLIC_KEY=12365182736
        - VALIDATE_SIGNATURES=false
        - TENANT_DATABASE_URL=postgres://postgres:root@postgres-tenant:5433/postgres
        # - DEFAULT_TENANT_ID= # This has a default value and dosen't hold much impact to the running of echo-server
        - JWT_SECRET=2d831fecf4065783c2779346c74dac9526481397bcf14320eb1f6e708e9d1a95
        - CLOUD_API_URL=
        - CLOUD_API_KEY=
        - CORS_ALLOWED_ORIGINS=*
        - FCM_API_KEY=
        - APNS_CERTIFICATE=
        - APNS_CERTIFICATE_PASSWORD=
        - APNS_TOPIC=
        - ANALYTICS_EXPORT_BUCKET=echo-export